import type { Metadata } from "next";
import Navbar from "@/components/navbar";
import { Toaster } from "sonner";
import Footer from "@/components/footer";
// import { Geist, Geist_Mono } from "next/font/google";
import { Nunito_Sans, Roboto, Kumbh_Sans } from "next/font/google";

const nunito = Nunito_Sans({ subsets: ["latin"], variable: "--font-nunito" });
const roboto = Roboto({ subsets: ["latin"], variable: "--font-roboto" });
const kumbh = Kumbh_Sans({ subsets: ["latin"], variable: "--font-kumbh" });
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Laxmi Crypto Funds",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${nunito.variable} ${roboto.variable} ${kumbh.variable} antialiased min-h-screen flex flex-col`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          <div className="container flex-grow mx-auto md:w-[80%] lg:w-[70%] xl:w-[55%] px-4 sm:px-6 md:px-8">{children}</div>
          <Footer />
          <Toaster theme="system" />
        </ThemeProvider>
      </body>
    </html>
  );
}
